server:
  port: 8080
# DataSource Config
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vuepress?serverTimezone=GMT%2B8
    username: root
    password: 123456
    hikari:
      connection-timeout: 30000
      auto-commit: true
      max-lifetime: 1800000
      pool-name: DatebookHikariCP
      minimum-idle: 5
      connection-test-query: SELECT 1
      idle-timeout: 30000
      maximum-pool-size: 50
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.entity
logging:
  level:
    com: debug




#默认请求参数
markdown:
#  笔记目录
  path: D:/linqin/vuepress-blog/docs
#  图片备份目录
  bak-path: ${markdown.path}/.vuepress/picBak
  # 本地图片
  local-path: ${markdown.path}/assets
  # 多久前编辑的不上传
  modify-day-not-upload: 28
  # 清空数据库后开启恢复，执行 /bak
  dataBaseBak: true


#推送到gitee
gitee:
  access_token: 8a5b58cd187031a2d5816ba3e82d7e92
  owner: linqin07
  repo: pic
  ref: master


# 支持的匹配规则
rule:
  upload:
    - \s*!\[.*\]\(assets\/.*\.(png|gif)\)$
    - \s*!\[.*\]\([^http|^assets].*\)$
    - \s*^<img src=.*>$
  check-replace: true
  http-upload: false
#  不处理的白名单
  white-list:
    - https://app.travis-ci.com/linqin07/vuepress-blog.svg?branch=master




